apiVersion: batch/v1
kind: Job
metadata:
  generateName: $USER-job-
  labels:
    eidf/user: $USER
    kueue.x-k8s.io/queue-name: $QUEUE_NAME
    kueue.x-k8s.io/priority-class: batch-workload-priority
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 172800
  template:
    metadata:
      labels:
        eidf/user: $USER
    spec:
      restartPolicy: Never
      containers:
      - name: huggingface
        image: huggingface/transformers-pytorch-gpu:latest 
        imagePullPolicy: IfNotPresent
        workingDir: "/workspace"
        command: ["/bin/bash", "-c"]
        args:
        - |
           export USER=root
           cd ./writeable/repos/open-r1_safety
           pip install uv
           rm -rf openr1_v2
           make -f Makefile_v2 install
           source openr1_v2/bin/install
           source .env
           apt-get update && apt-get install -y gettext
           bash git_login.sh
           git pull
           pwd
           VERSION=v00.15 envsubst < recipes/meta-llama/Llama-3.1-8B-Instruct/sft/config_distill_v00.15.yaml > temp_config.yaml && accelerate launch --config_file recipes/accelerate_configs/zero3_last.yaml --num_processes=4 src/open_r1/sft.py --config temp_config.yaml
        env:
          - name: MY_USERNAME
            value: $USER
          - name: MY_EXPERIMENT 
            value: experiment1
        resources:
           limits:
            nvidia.com/gpu: 4
            cpu: 16
            memory: 320Gi
        volumeMounts:
          - name: workspace
            mountPath: /workspace
            readOnly: true
          - name: writeable
            mountPath: /workspace/writeable
          - name: publicdata
            mountPath: /public
            readOnly: true
      nodeSelector:
       nvidia.com/gpu.product: NVIDIA-H200
      volumes:
        - name: workspace
          nfs:
            server: $NFS_SERVER_IP
            path: $WORKING_DIR
        - name: writeable
          persistentVolumeClaim:
             claimName: $MY_PVC
        - name: publicdata
          nfs:
            server: $INFORMATICS_NFS_SERVER_IP
            path: /public